version: '3.1'

services:
  pomodoro:
    container_name: pomodoro
    hostname: pomodoro
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
