version: '3.1'

services:
  spider-focus:
    container_name: spider-focus
    hostname: spider-focus
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
